net-name: x-net
lighthouse:
  light-1:
    groups: home
    nebula_ip:
      ipv4: 192.168.10.110/24
      ipv6: fd00:1234:5678:a::110/64
    port: '4242'
    public_ip: 13.13.14.40
    type: LH
  light-2:
    groups: home
    nebula_ip:
      ipv4: 192.168.10.101/24
      ipv6: fd00:1234:5678:a::101/64
    port: '4242'
    public_ip: 138.100.15.25
    type: LH
hosts:
  NL-H:
    groups: home
    nebula_ip:
      ipv4: 192.168.10.100/24
      ipv6: fd00:1234:5678:a::100/64
    public_ip: 31.58.33.31
    type: HOST
  RU:
    groups: home
    nebula_ip:
      ipv4: 192.168.10.101/24
      ipv6: fd00:1234:5678:a::101/64
    port: '4242'
    public_ip: 158.156.139.25
    type: HOST
  gpd:
    groups: home,ssh,admins
    nebula_ip:
      ipv4: 192.168.10.102/24
      ipv6: fd00:1234:5678:a::102/64
    type: HOST
  laptop-1:
    groups: home,ssh,admins
    nebula_ip:
      ipv4: 192.168.10.103/24
      ipv6: fd00:1234:5678:a::103/64
    type: HOST
  opi:
    groups: admins,ssh,home
    nebula_ip:
      ipv4: 192.168.10.105/24
      ipv6: fd00:1234:5678:a::105/64
    type: HOST
